# ####################################################################
# ################### CONFIGURATION VARIABLES ########################
# ####################################################################
IMAGE_NAME = "ubuntu/focal64"       # Image to use

MASTER_MEM = 2048                   # Amount of masters RAM
MASTER_CPU = 2                      # Number of masters processors
MASTER_NAME="master"                # Master node name

WORKER_MEM = 1024                   # Number of workers processors
WORKER_CPU = 1                      # Amount of workers RAM
WORKER_NBR = 2                      # Number of workers node

NODE_NETWORK_BASE = "192.168.50"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.base_mac = nil
    
    # Master node config
    config.vm.define MASTER_NAME do |master|
        
        # Hostname and network config
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "#{NODE_NETWORK_BASE}.10"
        master.vm.hostname = MASTER_NAME

        # RAM and CPU config for master
        master.vm.provider "virtualbox" do |v|
            v.memory = MASTER_MEM
            v.cpus = MASTER_CPU
        end
    end
    
    # Worker node config
    (1..WORKER_NBR).each do |i|
        config.vm.define "worker-#{i}" do |worker|
        
            # Hostname and network config
            worker.vm.box = IMAGE_NAME
            worker.vm.network "private_network", ip: "#{NODE_NETWORK_BASE}.#{i + 10}"
            worker.vm.hostname = "worker-#{i}"
            
            # RAM and CPU config for workers
            worker.vm.provider "virtualbox" do |v|
                v.memory = WORKER_MEM
                v.cpus = WORKER_CPU
            end
        end
    end
end
