- name: Metallb - Create Namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: metallb-system
        labels:
          app: metallb

- name: Metallb - Create secret
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      type: Opaque
      data:
        secretkey: nGZoSFnJ0DDxLfK/qMpzMQwmLWkvP+gfx3YkrB8ZXwPy6ICBKZMBr9/kqKV4tRpiq0G3Y8i3nBC+8Cd2p3HMS77xAalTeyN5leHzCznkzXiQByOHGPJKJIeRjcGbO5eZsz8II4CTrJMQBsJbdWhnU2HnJAFKHfmYOMRrrP5/lqw=

- name: Metallb - Create ConfigMap
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config
        namespace: metallb-system
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.50.240-192.168.50.250

- name: Install Metallb - Step2
  ansible.builtin.command:
    argv:
      - kubectl
      - apply
      - -f
      - https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml
