version: "2.2"
services:
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - "./data/db:/var/lib/mysql"
    working_dir: /var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    ports:
      - 8081:80

  php:
    build: ./docker/php
    restart: on-failure
    volumes:
      - "./:/var/www/html"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - php
