version: '3.7'
services:

  php:
    build:
      context: .
      dockerfile: './docker/php/Dockerfile'
    restart: on-failure
    volumes:
      - './:/var/www/html'
  
  nginx:
    image: nginx:latest
    restart: on-failure
    depends_on:
      - php
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

  mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
