version: '3.7'
services:

  php:
    image: php:7.2-fpm
    restart: on-failure
    volumes:
      - './:/var/www/html'
  
  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'