apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
  labels:
    storage-tier: images
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/images-pv/