apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage-tier: images