apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - camagru.com
        - db.camagru.com
      secretName: camagru-secret-tls
  rules:
    - host: camagru.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80
    - host: db.camagru.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pma-service
                port:
                  number: 80
