apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    storage-tier: database
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mysql-pv/