# - name: Copy kubeadm cluster config file to master
#   ansible.builtin.copy:
#     force: yes
#     src: ./roles/k8s-cluster-init/masters-init-cloud/files/config.yaml
#     dest: $HOME/config.yaml

- name: Create kubernetes cluster with kubeadm tool
  become: yes
  command:
    cmd: kubeadm init --ignore-preflight-errors=all --cri-socket /run/containerd/containerd.sock  --node-name="{{ tags.Name }}" --pod-network-cidr="10.244.0.0/16"
  tags:
    - cluster-create
