- name: Creating .kube directory
  ansible.builtin.file:
    path: $HOME/.kube/
    state: directory
    mode: 0755

- name: Configuring users cluster access
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ user }}/.kube/config"
    remote_src: yes
    owner: "{{ user }}"
    mode: 0700
