- name: get proper aws hostname
  become: yes
  ansible.builtin.uri:
    url: http://169.254.169.254/latest/meta-data/local-hostname
    return_content: yes
  register: hostname

- name: set proper aws hostname
  become: yes
  command:
    cmd: "hostnamectl set-hostname {{ hostname.content }}"
