apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    cloud-provider: "external"
controllerManager:
  extraArgs:
    configure-cloud-routes: "false"
    cloud-provider: "external"
kubernetesVersion: stable
