apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
clusterName: cloud-1
controllerManager:
  extraArgs:
    configure-cloud-routes: "false"
kubernetesVersion: stable
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: external
