- name: cloud - Ingress Rules for db and php apps
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress-rules
        namespace: default
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            if ($http_x_forwarded_proto = 'http') {
              return 301 https://$host$request_uri;
            }
      spec:
        rules:
          - host: "{{ app_host }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: app-service
                      port:
                        number: 80
          - host: "{{ pma_host }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: pma-service
                      port:
                        number: 80
  tags:
    - http
    - cloud

- name: local - Ingress Rules for db and php apps
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress-rules
        namespace: default
        annotations:
          kubernetes.io/ingress.class: nginx
      spec:
        tls:
          - hosts:
              - "{{ app_host }}"
              - "{{ pma_host }}"
            secretName: camagru-secret-tls
        rules:
          - host: "{{ app_host }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: app-service
                      port:
                        number: 80
          - host: "{{ pma_host }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: pma-service
                      port:
                        number: 80
  tags:
    - http
    - local
