- name: Ingress Rules for db and php apps
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress-rules
        namespace: default
        annotations:
          kubernetes.io/ingress.class: nginx
      spec:
        tls:
          - hosts:
              - allefebv.click
              - db.allefebv.click
            secretName: camagru-secret-tls
        rules:
          - host: allefebv.click
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: app-service
                      port:
                        number: 80
          - host: db.allefebv.click
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: pma-service
                      port:
                        number: 80
