- name: Disable taint on master for ingress-nginx installation
  ansible.builtin.command:
    argv:
      - kubectl
      - taint
      - node
      - master
      - node-role.kubernetes.io/master:NoSchedule-
  tags:
    - skip

- name: ingress-controller
  command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.46.0/deploy/static/provider/aws/deploy.yaml

- name: Workaround ingress admission
  command:
    cmd: kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
