ansible_host: "127.0.0.1"
ansible_user: "vagrant"
user: "vagrant"
ansible_private_key_file: "~/.vagrant.d/insecure_private_key"
network_interface: "enp0s8"
cloud_provider: ""
protocol: "https"
db_host: "mysql-service"
pma_host: "db.camagru.com"
dashboard_host: "dashboard.camagru.com"
app_host: "camagru.com"
