name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: dockerhub-login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: build-push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: allefebv/cloud-1:latest
      -
        name: digest
        run: echo ${{ steps.docker_build.outputs.digest }}